Models/EmailModel.cs
using System;

namespace mailApp.Models
{
    public class EmailModel
    {
        public Party From { get; set; }
        public Party To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Template Template { get; set; }
    }

    public class Party
    {
        public string FullName { get; set; }
        public string Email { get; set; }
    }

    public class Template 
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }

}

Models/ErrorViewModel.cs
using System;

namespace mailApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace mailApp.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FormSubmit()
        {
            var response = Request.Form["g-recaptcha-response"];
            var secretKey = "6LfI3gwbAAAAABudV2eHrLSkRh8chtC5ffc0ANRE";
            var client = new WebClient();
            var result = client.DownloadString(
                        string.Format(
                            "https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}",
                            secretKey,
                            response
                        ));

            var obj = JObject.Parse(result);
            var status = (bool)obj.SelectToken("success");
            ViewData["Message"] = status ? "Success" : "Failed";

            return View("Index");
        }

    }
}

Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;

namespace mailApp.Controllers
{
    public class DocumentController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        public DocumentController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GeneratePDF(string url)
        {
            HtmlToPdfConverter converter = new HtmlToPdfConverter();

            WebKitConverterSettings settings = new WebKitConverterSettings();
            settings.WebKitPath = Path.Combine(_hostingEnvironment.ContentRootPath, "QtBinariesWindows");
            converter.ConverterSettings = settings;

            PdfDocument document = converter.Convert(url);

            MemoryStream ms = new MemoryStream();
            document.Save(ms);
            document.Close(true);

            ms.Position = 0;

            FileStreamResult fileStreamResult = new FileStreamResult(ms, "application/pdf");
            fileStreamResult.FileDownloadName = "Syncfusion1.pdf";

            return fileStreamResult;
        }

        public class Data
        {
            public string Url { get; set; }
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mailApp.Models;
using SendGrid;
using SendGrid.Helpers.Mail;
using Newtonsoft.Json;
using System.Text;
using System.IO;

namespace mailApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public async Task<IActionResult> SendgridEmailSubmit([FromBody] List<EmailModel> emailModels)
        {

            ViewData["Message"] = "Email Sent!!!...";
            await Execute(emailModels);
            return View("Index");
        }

        static async Task Execute(List<EmailModel> emailModels)
        {
            var apiKey = Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
            var client = new SendGridClient(apiKey);

            foreach (var emailModel in emailModels)
            {
                var mail = new SendGridMessage
                {
                    From = new EmailAddress(emailModel.From.Email),
                    TemplateId = emailModel.Template.Id,
                    Personalizations = new List<Personalization>()
                };

                //var file = Directory.GetFiles(@"D:\Desktop\reddmail-public\wwwroot\Attachments").FirstOrDefault();
                //var bytes = System.IO.File.ReadAllBytes(file);
                //var attachment = Convert.ToBase64String(bytes);
                //mail.AddAttachment("Test.pdf", attachment);

                //ByteArrayOutputStream pdfBytes = createPdf();
                //String encodedPdf = new String(Base64.getEncoder().encode(pdfBytes.toByteArray()));

                var filePath = @"C:\Users\DELL\Desktop\Test.txt";
                byte[] byteData = Encoding.ASCII.GetBytes(System.IO.File.ReadAllText(filePath));
                mail.Attachments = new List<Attachment>
                {
                    new Attachment
                    {
                        Content = Convert.ToBase64String(byteData),
                        Filename = "Test.txt",
                        Type = "text/plain",
                        Disposition = "attachment",
                        ContentId = "Test.txt"
                    }
                };

                mail.Personalizations.Add(
                    new Personalization()
                    {
                        Tos = new List<EmailAddress>
                        {
                            new EmailAddress(emailModel.To.Email)
                        },
                        TemplateData = new TemplateData
                        {
                            Full_Name = emailModel.To.FullName,
                            Email = emailModel.To.Email,
                            Subject = emailModel.Subject,
                            Body = emailModel.Body
                        }
                    });
                var response = await client.SendEmailAsync(mail);
            }

        }

        public class TemplateData
        {
            public string Full_Name { get; set; }
            public string Email { get; set; }
            public string Subject { get; set; }
            public string Body { get; set; }

        }

    }
}

Views/Document/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Document page</h1>
<div>
    @using (Html.BeginForm("GeneratePDF", "Document", FormMethod.Post))
    {
        <div>
            @Html.Label("URL: ")
            @Html.TextBox("url")
        </div>
        <input id="btnSubmit" type="submit" value="Submit" />
    }

</div>

@*<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    var btn_submit = document.getElementById("btnSubmit");
    var url = document.getElementById("url");
    btn_submit.addEventListener('click', () => submitForm(url.value));

    function submitForm(url) {
        console.log({ url: JSON.stringify(url) });
        $.ajax({
            url: '/Document/GeneratePDF',
            data: JSON.stringify(url),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            type: "POST",
        });
    }

</script>*@

Views/Home/Index.cshtml
@model EmailModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="row row-title">
    <div class="bg-title col-md-5">
        <h1 class="display-4">Welcome To</h1>
        <h2 class="display-2">REDD</h2>
    </div>
    <div class="bg-title2 col-md-5">
        <h3>Quick Mail Service For Effective Collaboration.</h3>
    </div>
</div>
<div class="row row-form">
    @*<div class="bg-img col-md-6">
            <img id="image" src="~/Assets/person1.png">
        </div>*@
    <div class="bg-form col-md-6">
        <form id="form">
            <h1 class="title-new-email">New Email</h1>
            <label>From: </label>
            <input id="sender_email" name="Email" class="email-input email-from" type="text" placeholder="Sender's email address" value="kamalshanth@peachit.lk" />
            <input id="sender_fullname" class=" email-input email-from" type="text" placeholder="Sender's Fullname" value="Kamalshanth Selvarajah" />

            <label>To: </label>
            <input id="receiver_email" class="email-input email-to" type="text" placeholder="Receiver's email address" />
            <input id="receiver_fullname" class=" email-input email-from" type="text" placeholder="Receiver's Fullname" />

            <label>Content: </label>
            <input id="subject" class="email-input email-sub" type="text" placeholder="Enter your subject" />
            <textarea id="message" class="email-msg" placeholder="Enter your message"></textarea>

            <label>Select a Template </label>
            <select name="templates" id="templates" class="email-input templates">
                <option value='{"id":"d-743590e5c36341b1abb64259ed55d969","name":"welcome"}'>Welcome</option>
                <option value='{"id":"d-f30c1543f5894f9eb30cd3f0fd4571f9","name":"services"}'>Service</option>
            </select>

            <label for="myfile">Select a Attachment</label>
            <input type="file" id="file" name="myfile">

            <button id="btn_add" type="submit" value="Add">Add</button>
        </form>
    </div>

    <div class="bg-emails col-md-6">
        <div class="emails-section">
            <h1 class="title-emails">Emails Queue
                <span id="emails_count">0</span>
            </h1>
            <div id="email_list"></div>
            <button id="btn_send">Send</button>
        </div>
    </div>

</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReddMail</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Assets/ReddLogo.PNG" alt="REDD" />
                    MailApp
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Document" asp-action="Index">Document</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container bg-footer">
            &copy; 2021 - mailApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script>
        $(document).ready(function () {
            @*console.log("ready!");
            alert("ready");*@
        });
    </script>
</body>
</html>